# /*---------------------------------------------------------------------------8
# |                                                                            |
# |     This workflows deploys the SAP Workload Zone with GitHub Actions       |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

name: Deploy SAP Workload Zone
run-name: Deploy SAP Workload Zone by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      deployer:
        description: "Deployer configuration name, use the following syntax: ENV-LOCA-VNET-INFRASTRUCTURE"
        required: true
        type: environment
      workload_zone:
        description: "Workload zone configuration name, use the following syntax: ENV-LOCA-VNET-INFRASTRUCTURE"
        required: true
        type: environment
      # workload_environment:
      #   description: "Workload environment (DEV, QA, PRD, ...)"
      #   required: true
      #   type: string
      #   default: DEV
      inherit_settings:
        description: "Inherit Terraform state file information from control plane"
        type: boolean
        default: true
      test:
        description: "Test the deployment without actually deploying the resources"
        type: boolean
        default: false

permissions:
  contents: write
  id-token: write
  issues: write

jobs:
  deploy_sap_workload_zone:
    name: Deploy SAP Workload Zone
    environment: ${{ inputs.workload_zone }}
    runs-on: self-hosted
    container:
      image: ghcr.io/nnoaman/sap-automation:github_actions
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get app token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          #organization: ${{ github.repository_owner }}

      - name: Azure Login
        uses: Azure/Login@v2
        with:
          creds: '{"clientId":"${{ secrets.WL_ARM_CLIENT_ID }}","clientSecret":"${{ secrets.WL_ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.WL_ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.WL_ARM_TENANT_ID }}"}'

      - name: Deploy SAP Workload Zone
        run: |
          cd ${SAP_AUTOMATION_REPO_PATH}
          deploy/automation/02-deploy-sap-workload-zone/01-deploy-sap-workload-zone.sh
        env:
          APP_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          CP_ARM_CLIENT_ID: ${{ secrets.CP_ARM_CLIENT_ID }}
          CP_ARM_CLIENT_SECRET: ${{ secrets.CP_ARM_CLIENT_SECRET }}
          CP_ARM_SUBSCRIPTION_ID: ${{ secrets.CP_ARM_SUBSCRIPTION_ID }}
          CP_ARM_TENANT_ID: ${{ secrets.CP_ARM_TENANT_ID }}
          WL_ARM_CLIENT_ID: ${{ secrets.WL_ARM_CLIENT_ID }}
          WL_ARM_CLIENT_SECRET: ${{ secrets.WL_ARM_CLIENT_SECRET }}
          WL_ARM_SUBSCRIPTION_ID: ${{ secrets.WL_ARM_SUBSCRIPTION_ID }}
          WL_ARM_TENANT_ID: ${{ secrets.WL_ARM_TENANT_ID }}
          WL_ARM_OBJECT_ID: ${{ secrets.WL_ARM_OBJECT_ID }}
          TEST_ONLY: ${{ inputs.test }}
          deployerconfig: ${{ inputs.deployer }}.tfvars
          deployerfolder: ${{ inputs.deployer }}
          inherit: ${{ inputs.inherit_settings }}
          workload_zone_folder: ${{ inputs.workload_zone }}
          workload_zone_configuration_file: ${{ inputs.workload_zone }}.tfvars
          APP_CONFIGURATION_NAME: ${{ vars.APP_CONFIGURATION_NAME }}
